# Generated by Django 5.1.1 on 2024-09-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_dob_account_max_otp_try_account_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='max_otp_try',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
