# Generated by Django 5.1 on 2024-08-30 22:12

import diplome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='id',
            field=models.CharField(default=diplome.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
