# Generated by Django 5.1 on 2024-09-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0002_alter_diploma_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diploma',
            options={'ordering': ['-created']},
        ),
    ]
