# Generated by Django 5.1.1 on 2024-09-08 23:41

import documents.models
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=documents.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('diploma', models.FileField(upload_to=documents.models.diploma_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
