# Generated by Django 5.1.1 on 2024-09-21 23:36

import django.db.models.deletion
import django_extensions.db.fields
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=documents.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('diploma', models.FileField(upload_to=documents.models.diploma_upload_path)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DemandeSoumission',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.CharField(default=documents.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('titre', models.CharField(max_length=120)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'SOUMIS'), (2, 'TRAITER'), (3, 'RECEPTION'), (4, 'FIN DE TRAITEMENT'), (5, 'REJET')], default=1)),
                ('etudiants', models.ManyToManyField(to='accounts.diplome')),
                ('diplome', models.ManyToManyField(to='documents.diploma')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.diplome')),
            ],
        ),
        migrations.AddField(
            model_name='diploma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='documents.etudiant'),
        ),
    ]
