# Generated by Django 5.1.1 on 2024-09-22 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandesoumission',
            name='etudiants',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandesoumission',
            name='status',
            field=models.IntegerField(choices=[(1, 'SOUMIS'), (2, 'TRAITE'), (3, 'RECEPTION'), (4, 'FIN DE TRAITEMENT'), (5, 'REJET')], default=1),
        ),
    ]
