# Generated by Django 5.1.1 on 2024-09-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_demandesoumission_etudiants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diploma',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.AddField(
            model_name='demandesoumission',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diploma',
            name='etudiant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.etudiant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='first_name',
            field=models.CharField(default='kamal', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='last_name',
            field=models.CharField(default='last name', max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='phone_number',
            field=models.CharField(default=775726004, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
