# Generated by Django 5.1.1 on 2024-09-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_diploma_user_remove_etudiant_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandesoumission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
