# Generated by Django 5.1.1 on 2024-09-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_demandesoumission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='type_diplome',
            field=models.IntegerField(choices=[(1, 'BTS'), (2, 'CAP'), (3, 'BEP')], default=1),
        ),
    ]
